### ISSUE TITLE
Error to start crawler

### ISSUE THREAD

**Issue by zafai** [MA3STR0/kimsufi-crawler#17]
Hello Guys,

when i try to start the crawler i get this error:

root@server:~/kimsufi-crawler# python crawler.py
2015-02-12 21:46:41,663 Cannot connect to your SMTP account. Correct your config and try again. Error details:
2015-02-12 21:46:41,664 character mapping must return integer, None or unicode
2015-02-12 21:46:41,664 Notifier loading failed,check configuration for errors
Traceback (most recent call last):
  File "crawler.py", line 124, in <module>
    notifier = getattr(n_module, n_classname)(config)
  File "/root/kimsufi-crawler/notifiers/email_notifier.py", line 26, in __init__
    super(EmailNotifier, self).__init__(config)
  File "/root/kimsufi-crawler/notifiers/base_notifier.py", line 12, in __init__
    self.check_requirements()
  File "/root/kimsufi-crawler/notifiers/email_notifier.py", line 37, in check_requirements
    server.login(self.fromuser, self.frompwd)
  File "/usr/lib/python2.7/smtplib.py", line 598, in login
    (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
  File "/usr/lib/python2.7/smtplib.py", line 562, in encode_cram_md5
    response = user + " " + hmac.HMAC(password, challenge).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 72, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

Python 2.7.3
tornado 4.0.2

I check my SMTP Setting in a Local Thunderbird and the are working!

Thanks for your help in advance.

**Comment by MA3STR0** [comment]
It looks like a 4 years old bug in hmac module that affects smtplib: http://bugs.python.org/issue5285

Pull the code and try again with an update I just added.

Do you have unicode characters in login/pass/smtp_host?

**Comment by zafai** [comment]
Thanks now it works issue close
