### ISSUE TITLE
Notifier loading failed

### ISSUE THREAD

**Issue by Varity** [MA3STR0/kimsufi-crawler#25]
Hi, 

i tried to get your crawler on my server, but after following your "guide", i am getting this error:

> [root@titanium kimsufi-crawler]# python crawler.py
2015-03-25 11:23:59,022 Notifier loading failed,check configuration for errors
Traceback (most recent call last):
  File "crawler.py", line 166, in <module>
    NOTIFIER = getattr(NOTIFIER_MODULE, NOTIFIER_CLASSNAME)(CONFIG)
  File "/root/kimsufi-crawler/notifiers/email_notifier.py", line 26, in __init__
    super(EmailNotifier, self).__init__(config)
  File "/root/kimsufi-crawler/notifiers/base_notifier.py", line 12, in __init__
    self.check_requirements()
  File "/root/kimsufi-crawler/notifiers/email_notifier.py", line 30, in check_re                                                      quirements
    server = smtplib.SMTP(self.host, self.port)
  File "/usr/lib64/python2.7/smtplib.py", line 250, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 310, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 285, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> gaierror: [Errno -2] Name or service not known

Do you can identify this one? Did i do something wrong? Running this on CentOS

**Comment by MA3STR0** [comment]
Hi,

Failure in SMTP connection usually it means wrong email/password, in your case of "service not known" my guess would be wrong `from_smtp_host`. If you use some exotic mail it may also be some special setting like `use_starttls`.

Try to double-check smtp settings and/or run the script on a different machine. If it still does not work tell me what email provider you use.

**Comment by Varity** [comment]
Hi,
everything is working fine now. I changed the provider from gmail to outlook. Another mistake could be the wrong installation of tornado and i just installed "yum install gcc python-devel".
