### ISSUE TITLE
ImportError: cannot import name SmsApi

### ISSUE THREAD

**Issue by naNaaR** [MA3STR0/kimsufi-crawler#56]
did something wrong?

```
{
    "servers": ["KS-1"],
    "region": "europe",
    "notifier": "smsapi",
    "smsapi_username": "mail@address.com",
    "smsapi_password": "<(MD5password)>",
    "smsapi_recipient": "4879000****",
    "crawler_interval": 30,
    "request_timeout": 30
}
```

```
$ python crawler.py 
2016-06-09 13:59:14,788 Notifier loading failed, check config for errors
Traceback (most recent call last):
  File "crawler.py", line 146, in <module>
    _NOTIFIER_MODULE = importlib.import_module(_NOTIFIER_FILE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/iscolor/kimsufi-crawler/notifiers/smsapi_notifier.py", line 6, in <module>
    from smsapi import SmsApi
ImportError: cannot import name SmsApi

```

**Comment by MA3STR0** [comment]
I think it complains not about loading a notifier plugin class itself, but about dependency of that plugin. Try installing https://pypi.python.org/pypi/python-smsapi

**Comment by naNaaR** [comment]
i`ve alredy done that. `even pip install smsapi `doesn`t fix it.

**Comment by MA3STR0** [comment]
Sure you've done it in right environment? Try just running a python shell and executing `from smsapi import SmsApi`, would that throw an exception too?

**Comment by naNaaR** [comment]
Yep, from python console it was ok. 
I dont know how, and dont know why, but it start working.
Thank you!
