### ISSUE TITLE
Telegram no working

### ISSUE THREAD

**Issue by jkvint** [MA3STR0/kimsufi-crawler#72]
python crawler.py
2019-09-12 11:59:10,063 Notifier loading failed, check config for errors
Traceback (most recent call last):
  File "crawler.py", line 190, in <module>
    NOTIFIER = getattr(_NOTIFIER_MODULE, _NOTIFIER_CLASSNAME)(_CONFIG)
  File "/home/jkvint/kimsufi-crawler/notifiers/telegram_notifier.py", line 18, in __init__
    super().__init__(config)

**Comment by jkvint** [comment]
Only error left  No answer from API: {'answer': None, 'version': '1.0', 'error': {'__class': 'result:error', 'value': None, 'status': '252', 'exceptionType': 'Unavailable', 'message': "Unknown function 'dedicated#getAvailability2'"}, 'id': 0}

**Comment by jkvint** [comment]
Can you check the script? Problem with api?
